[alembic]
name = Enterprise AI Customer Support Assistant
script_location = alembic
sqlalchemy.url = postgresql://postgres:password@localhost:5432/enterprise_ai

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = warn
handlers = console
qualname =

[logger_sqlalchemy]
level = warn
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = info
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datetime_fmt = %Y-%m-%d %H:%M:%S